import { Serie } from "./serie.js";

export const series = [
    new Serie (1,"Breaking Bad","AMC", 5,"Set and filmed in Albuquerque, New Mexico, the series tells the story of Walter White, a struggling and depressed high school chemistry teacher who is diagnosed with lung cancer", "https://www.amc.com/shows/breaking-bad","https://i0.wp.com/www.gamerfocus.co/wp-content/uploads/2014/08/BreakingBad-2.jpg?w=1480&ssl=1") ,
    
    new Serie (2,"Orange Is the New Black", "Netflix", 6, "The series begins revolving around Piper Chapman, a woman in her thirties living in New York City who is sentenced to 15 months in Litchfield Penitentiary", "https://www.netflix.com/co/title/70242311","https://fotografias.antena3.com/clipping/cmsimages01/2018/07/23/53FC68B5-1AAA-4D53-964B-BBA54717616C/97.jpg?crop=2423,1363,x0,y1104&width=1600&height=900&optimize=high&format=webply"),
    
    new Serie (3, "Game of Thrones","HBO", 7, "American fantasy drama", "https://www.hbo.com/game-of-thrones", "https://img.huffingtonpost.com/asset/5ca76cbb24000064010442ea.jpeg?cache=cIMtmi10Bz&ops=1200_630"),

    new Serie (4, "The Big Bang Theory", "CBS", 12, "Leonard and Sheldon are brilliant physicists—geniuses in the laboratory but socially challenged everywhere else. Enter beautiful, street-smart neighbor Penny, who aims to teach them a thing or two about life. Despite their on-again, off-again relationship in the past, Leonard and Penny have finally gotten married. Even Sheldon has found a female companion, entering into a relationship agreement with neurobiologist Amy Farrah Fowler, and he recently took their relationship to the next level by marrying her after a long courtship. In their free time, Leonard and Sheldon enjoy fantasy role-playing games with their ever-expanding universe of friends, including fellow scientists Koothrappali, Wolowitz, and Wolowitz’s adorable microbiologist wife, Bernadette, who is adjusting to life with their two children.", "https://www.cbs.com/shows/big_bang_theory/about/", "https://www.lifeboxset.com/wp-content/uploads/2019/02/20190211_170119084061-the-big-bang-theory.jpg"),
    
    new Serie (5, "Sherlock", "BBC",  4, "Sherlock depicts consulting detective Sherlock Holmes (Benedict Cumberbatch) solving various mysteries in modern-day London. Holmes is assisted by his flatmate and friend, Dr John Watson (Martin Freeman), who has returned from military service in Afghanistan with the Royal Army Medical Corps", "https://www.bbc.co.uk/programmes/b018ttws", "https://wallpapercosmos.com/w/full/a/d/9/13639-1920x1200-desktop-hd-sherlock-tv-series-background-photo.jpg"),

    new Serie (6, "A Very English Scandal", "BBC", 2, "A Very English Scandal is a fact-based three-part British television comedy-drama miniseries based on John Preston's book of the same name.", "https://www.bbc.co.uk/programmes/p065smy4", "https://1.bp.blogspot.com/-7KUAn18sC4A/W2PaWFHHHpI/AAAAAAAAKDY/gRU5vZ54FPw1s7k1iwBiLRpEBEAqcwM-wCLcBGAs/s320/A%2BVery%2BEnglish%2BScandal%2B-%2BKRC.jpg"),
];
   